=== guigolab/rnaget-beacon-demo/beacon-schemas/expressionValue.json
{
    "$comment": "version: ga4gh-beacon-expressionValues-v2.0.0",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "description": "Schema for an expression value entry. It represents the expression value of a specific biosample for a specific feature in a specific matrix.",
    "properties": {
        "id": {
            "description": "Internal expression value ID. It is a unique identifier for the expression value.",
            "examples": [
                "expressionValue-001"
            ],
            "type": "string"
        },
        "biosampleId": {
            "description": "Reference to the biosample ID.",
            "examples": [
                "008dafdd-a3d1-4801-8c0a-8714e2b58e48"
            ],
            "type": "string"
        },
        "value": {
            "description": "Value of the expression value.",
            "examples": [
                "100"
            ],
            "type": "number"
        },
        "featureId": {
            "description": "Reference to the feature ID.",
            "examples": [
                "ENSG00000000000"
            ],
            "type": "string"
        },
        "matrixId": {
            "description": "Reference to the matrix ID.",
            "examples": [
                "matrix-gene-expression-001"
            ],
            "type": "string"
        },
        "info": {
            "$ref": "../common/info.json"
        }
    },
    "required": [
        "biosampleId",
        "value",
        "featureId",
        "matrixId",
        "id"
    ],
    "title": "Expression value",
    "type": "object"
}

=== guigolab/rnaget-beacon-demo/server/beacon/fixtures/data/expressionValues.json
[
  {
    "id": "expressionValue-001",
    "biosampleId": "008dafdd-a3d1-4801-8c0a-8714e2b58e48",
    "featureId": "ENSG00000141510.18",
    "matrixId": "matrix-gene-expression-001",
    "value": 100
  },
  {
    "id": "expressionValue-tp53-gse88557-001",
    "biosampleId": "008dafdd-a3d1-4801-8c0a-8714e2b58e48",
    "featureId": "ENSG00000141510.18",
    "matrixId": "GSE88557",
    "value": 1247.5
  },
  {
    "id": "expressionValue-002",
    "biosampleId": "sample-example-0001",
    "featureId": "ENSG00000141510.18",
    "matrixId": "matrix-gene-expression-001",
    "value": 42.5
  }
]
